/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-04-06

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"

/*
 * 	PA9 - usart 1 TX
 * 	PA10 - usart 1 RX
 */
void init_gpio_as_AF_for_usart() {
	//1
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	//2
	GPIOA->MODER |= GPIO_MODER_MODER9_1 | GPIO_MODER_MODER10_1;
	GPIOA->AFR[1] |=  (1 << 4)|(1 << 8);	//AF1

	//3 - turn on peripheral...
}

void init_usart1() {

	//0 (3)
	init_gpio_as_AF_for_usart();
	//1
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;
	//2

	USART1->CR1 |= USART_CR1_RE;	//enable receive
	USART1->CR1 |= USART_CR1_TE;	//transmit enable
	USART1->CR2 &= ~USART_CR2_STOP;	//1 stop bit

	USART1->BRR = SystemCoreClock / 115200;

	//4
	USART1->CR1 |= USART_CR1_UE;
}

uint8_t put_char_usart1(uint8_t byte) {
	if ((USART1->ISR & USART_ISR_TXE) == USART_ISR_TXE)
	{
		USART1->TDR = byte;
		return 1;
	}
	return 0;
}


int main(void)
{
	init_usart1();

	uint8_t byte = 0;

	while (1)
	{
		if (put_char_usart1(byte) == 1) {
			byte++;
		}

	}
}
